@startuml
class Movie{
+plump
}

class AbstractMovie{
+plump()
}

class User{
+id:str
+preference:str
}

class Cine{
+seat_vip:int
+seat_regular:int
+user()
+user_register()
+films()
+available()
+sell()
}

AbstractMovie --|> ABC
AbstractMovie --|> Movie
User --* Cine
@enduml